edit build script a bit

diff --git a/deploy/main.yml b/deploy/main.yml
--- a/deploy/main.yml
+++ b/deploy/main.yml
@@ -108,41 +108,40 @@ Resources:
       KeyName: 'lucretia-key-pair-2022'
       UserData:
         Fn::Base64: !Sub |
-            #!/bin/bash -xe
+          #!/bin/bash -xe
 
-            # send script output to /tmp so we can debug boot failures
-            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
+          # send script output to /tmp so we can debug boot failures
+          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
 
-            echo 'running yum update...'
-            yum -y update
-            yum install -y gcc make tcl aws-cfn-bootstrap
+          echo 'running yum update...'
+          yum -y update
+          yum install -y gcc make tcl aws-cfn-bootstrap
 
-            # Create log directory
-            mkdir -p /home/ec2-user/app/logs
-            
-            echo 'running cfn-init metadata file + package install...'
-            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
+          # Create log directory
+          mkdir -p /home/ec2-user/app/logs
+          
+          echo 'running cfn-init metadata file + package install...'
+          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
 
-            echo 'installing redis...'
-            mkdir /etc/redis
-            mkdir -p /var/redis/6379
-            make -C /home/ec2-user/redis-stable/ distclean
-            make -C /home/ec2-user/redis-stable/
-            cp /home/ec2-user/redis-stable/utils/redis_init_script /etc/init.d/redis_6379
-            cp /home/ec2-user/redis-stable/src/redis-server /usr/local/bin
-            cp /home/ec2-user/redis-stable/src/redis-cli /usr/local/bin
+          echo 'installing redis...'
+          mkdir /etc/redis
+          mkdir -p /var/redis/6379
+          make -C /home/ec2-user/redis-stable/ distclean
+          make -C /home/ec2-user/redis-stable/
+          cp /home/ec2-user/redis-stable/utils/redis_init_script /etc/init.d/redis_6379
+          cp /home/ec2-user/redis-stable/src/redis-server /usr/local/bin
+          cp /home/ec2-user/redis-stable/src/redis-cli /usr/local/bin
 
-            echo 'downloading cloudwatch configs...'
-            echo 'directory: $(pwd)'
-            aws s3api get-object --bucket lucretia-bott-config --key amazon-cloudwatch-agent.json /home/ec2-user/agents/amazon-cloudwatch-agent.json
-            aws s3api get-object --bucket lucretia-bott-config --key redis.conf /etc/redis/6379.conf
-            chkconfig redis_6379 on
+          echo 'downloading cloudwatch configs...'
+          aws s3api get-object --bucket lucretia-bott-config --key amazon-cloudwatch-agent.json /home/ec2-user/agents/amazon-cloudwatch-agent.json
+          aws s3api get-object --bucket lucretia-bott-config --key redis.conf /etc/redis/6379.conf
+          chkconfig redis_6379 on
 
-            echo 'initializing cloudwatch...'
-            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/home/ec2-user/agents/amazon-cloudwatch-agent.json -s
+          echo 'initializing cloudwatch...'
+          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/home/ec2-user/agents/amazon-cloudwatch-agent.json -s
 
-            echo 'signaling instance is ready...'
-            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
+          echo 'signaling instance is ready...'
+          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance
       Tags:
         - Key: Name
           Value: !Ref AWS::StackName
